### ISSUE TITLE
R-250 Quitar recuperados, muertes y confirmados porque ya no son esos criterios. [2]

### ISSUE THREAD

**Issue by alejocruzrcc** [pasosdeJesus/sivel2_gen#252]

**Comment by vtamara** [comment]
Aún falta lo central de este requerimiento que es no tomar datos de covid19.health sino de la misma instancia de SIVeL o de base.nocheyniebla.org (sería ideal que fuese configurable el URL al cual consultar).

**Comment by vtamara** [comment]
Cerrado con https://github.com/pasosdeJesus/mapa_tiempo_yi_liu/pull/10
