### ISSUE TITLE
R-251 Que el Select de de MapNavbar donde se seleccionaban los paises por continente y Global, únicamnete quede Colombia, Además borrar datos y strinfgs de Map Text de los otros países que ahí se llaman [2]

### ISSUE THREAD

**Issue by alejocruzrcc** [pasosdeJesus/sivel2_gen#254]

**Comment by vtamara** [comment]
![Captura de pantalla de 2020-10-01 16-05-01](https://user-images.githubusercontent.com/701221/94863324-46435780-0408-11eb-934e-8a0becc028e4.png)

**Comment by vtamara** [comment]
Implementado en https://github.com/pasosdeJesus/mapa_tiempo_yi_liu/pull/3
