### ISSUE TITLE
Falla al presentar formulario de caso tras activar Administrar->Ficha Vertical

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#299]

**Comment by vtamara** [comment]
Resuelto con https://github.com/pasosdeJesus/sivel2_gen/commit/6621d87f52dd845d43c10b3542b3e416ed01cd6f

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2020-12-21 09-24-58](https://user-images.githubusercontent.com/10052756/102787107-8ca4b480-436e-11eb-9f50-bdf82e8bfd17.png)
Al crear nuevo caso genera error
