### ISSUE TITLE
F- 39 Al crear caso > basico > region  no guarda la información y genera error.

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#3]
F- 39 Al crear caso > basico > region  no guarda la información y genera error.

**Comment by BlancaInesAcosta** [comment]
![captura de pantalla de 2017-06-07 14-55-37](https://user-images.githubusercontent.com/10052756/26898522-ef4e06aa-4b91-11e7-94b2-dda9306dc0ac.png)

**Comment by vtamara** [comment]
Resuelto
