### ISSUE TITLE
R-312 En presunto responsable unificar división / brigada / batallón en un sólo campo (homologar información existente con una migración que concatene lo de los 3 campos en el nuevo --separar con punto) [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#312]

**Comment by alejocruzrcc** [comment]
https://github.com/pasosdeJesus/sivel2_gen/pull/815

**Comment by vtamara** [comment]
Actualmente se ve asi:
![image](https://user-images.githubusercontent.com/701221/196042078-b17760fd-0307-46a9-b29b-c92ddb3c2b88.png)


Los tres campos División/Brigada/Batallón debería quedar en uno sólo y en este ejemplo el contenido debería ser ""

**Comment by vtamara** [comment]
Se completó con https://github.com/pasosdeJesus/sivel2_gen/commit/78f7b959b88c468f318a645060ad70e59e40c920
