### ISSUE TITLE
F-328 En rol operador en reportes y conteos >> listado de victimas y casos, el filtro de muerto DH 0 aparece 3 veces 

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#331]
![Captura de pantalla de 2020-12-27 12-30-10](https://user-images.githubusercontent.com/10052756/103176675-b021a080-4841-11eb-8395-1d9af3a0c08d.png)

**Comment by vtamara** [comment]
No ocurre en otras instalaciones:
![image](https://user-images.githubusercontent.com/701221/154573901-817e4bd5-55bc-484d-b174-985c9ccbca83.png)

En un sitio de de desarrollo se ve una configuración difente de 
![image](https://user-images.githubusercontent.com/701221/154574516-b585ad91-6097-497e-824d-7d7e2846033c.png)
