### ISSUE TITLE
R-349 Hacer un control para ingresar coordenadas en otras notaciones y usarlo en campos latitud y longitud  de #343 [6]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#349]
Podría ser un icono en los campos latitud, longitud  que al pulsarse abra un dialogo modal que permita:
1. elegir un formato de las coordenas.  Debe por lo menos permitir elegir decimal grados, minutos y segundos en el mismo sistema de coordenadas WGS-1984 --como los puntos del ejemplo del formulario #343 .  Pero debe dar espacio para elegir otros sistemas de coordenadas --como MAGNA SIRGAS.
2. que permita especificar la latitud y la longitud en ese formato
3. que calcule y presente en el mismo dialogo modal el valor convertido de la coordenada --ideal previsualizar sobre mapa con eso se verifica que la conversión tuvo sentido.
4. que con un botón "Insertar" ponga esa latitud y longitud en formato web mercator en el formulario.

**Comment by alejocruzrcc** [comment]
Docuemento de desarrollo: 
https://docs.google.com/document/d/1ZSLOEAycsXCd-3NrKHvrVWDIPykIXWQDfaBnqO-r8vs/edit?usp=sharing

**Comment by vtamara** [comment]
Documento de referencia https://www.igac.gov.co/sites/igac.gov.co/files/tipos_de_coordenadas.pdf

**Comment by vtamara** [comment]
Implementación con https://github.com/pasosdeJesus/apo214/pull/45

![SIVeL 2-0b14 10-5-2021 8-25-13 p- m-](https://user-images.githubusercontent.com/701221/117744301-0af2dd80-b1ce-11eb-9a01-ecd30d1607f7.png)


Documentación inicial en: https://github.com/pasosdeJesus/apo214/blob/main/doc/control_geolocalizacion.md
