### ISSUE TITLE
F-353 En un formulario aunque tiene nombre interno dice que " En 'Campo' es demasiado corto el valor de 'Nombreinterno' (mínimo 1 carácter) En 'Campo' falta un valor para 'Nombreinterno' Sólo debe tener caracteres alfanuméricos en minusculas y _"

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#353]
![Captura de pantalla de 2021-02-01 14-58-57](https://user-images.githubusercontent.com/10052756/106533274-d3ceab00-64bf-11eb-9ab7-0a167a8dfb15.png)

**Comment by vtamara** [comment]
No tomo el pantallazo completo y no parece error, sino que como dice el mensaje no llenó el campo.
![screencapture-192-168-0-99-3000-sivel2-formularios-1-2021-02-07-22_50_28](https://user-images.githubusercontent.com/701221/107173875-e69d2000-6996-11eb-9621-e6b5830e912c.png)
