### ISSUE TITLE
F-365 Desde resumen de caso, no permite descargar anexos (reportado por Daniela)

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#365]
![The page you were looking for doesn-t exist -404- 27-2-2021 8-23-14 a- m-](https://user-images.githubusercontent.com/701221/109388439-0c9e4c00-78d5-11eb-92fa-4b99fd181625.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-03-27 11-43-49](https://user-images.githubusercontent.com/10052756/112727707-c814c900-8ef1-11eb-80dc-54365ed1fd34.png)
En sitio de desarrollo se puede descargar el anexo pero se ve este error

**Comment by vtamara** [comment]
Este error ocurre cuando la aplicación se monta en /.  Pero no ocurre cuando está montada en /sivel2
