### ISSUE TITLE
R-366 Desde resumen de caso que sea posible pre-visualizar anexo (con tipo soportado digamos .jpg, .png y .pdf) por ejemplo al pasar por encima el cursor en un dialogo modal que ocupe mas o menos un tercio de la pantalla [3]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#366]

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/194109431-db3f1421-9047-430c-b469-aab1ab80dc82.MOV

**Comment by vtamara** [comment]
La propuesta hasta el momento está bien con un botón. Lo que no está bien respecto al requerimiento es que ocupa más de un tercio de la pantalla:

![image](https://user-images.githubusercontent.com/701221/194164423-cf04e4ea-1d17-42d9-a9bd-4e199c0b000c.png)

**Comment by vtamara** [comment]
PDF a lo alto si parece limitado pero no a lo ancho.
![image](https://user-images.githubusercontent.com/701221/194165351-b743ebd5-61ee-4a33-acc1-1f5c3b6069bc.png)

**Comment by vtamara** [comment]
No se ven bien los botónes cuando el nombre del archivo es grande:
![Motor de SIVeL genérico 6-10-2022 2-51-12 p- m-](https://user-images.githubusercontent.com/701221/194406057-55e168aa-a714-4233-88c7-10f96a4f057f.png)
