### ISSUE TITLE
F-385 Al crear una plantilla nueva plantillahcm genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#385]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-04-27 17-55-05](https://user-images.githubusercontent.com/10052756/116322769-547d0a80-a782-11eb-88e6-4019638c0baf.png)

**Comment by vtamara** [comment]
Resuelto.
