### ISSUE TITLE
F-393 No exporta ni importa combatientes [1]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#394]

**Comment by alejocruzrcc** [comment]
Se visualiza que si exporta combatientes en listado y en registro
![Captura de pantalla de 2021-06-01 00-09-03](https://user-images.githubusercontent.com/12545631/120272585-fbb5fb80-c272-11eb-93a9-806d910b3ee3.png)
![Captura de pantalla de 2021-06-01 00-07-49](https://user-images.githubusercontent.com/12545631/120272712-21db9b80-c273-11eb-99fb-4ff4998d2ed1.png)

**Comment by alejocruzrcc** [comment]
Actualmente no esta importando... se queda cargando la página.

**Comment by vtamara** [comment]
Nos referimos a exportación en XRLAT e importación de XRLAT.

**Comment by alejocruzrcc** [comment]
Pruebas:
Exportando combatientes....
![Captura de pantalla de 2021-06-09 19-38-26](https://user-images.githubusercontent.com/12545631/121449524-9c857480-c95f-11eb-97e9-5d340a0e1382.png)

Importando combatientes:
![Captura de pantalla de 2021-06-09 19-38-14](https://user-images.githubusercontent.com/12545631/121449555-a9a26380-c95f-11eb-9994-d49e9544f26a.png)

**Comment by vtamara** [comment]
Implementación con #410 . Aunque:
* cambiar elementos para coincidir con otros existentes:  <profesion> debería ser <ocupacion>
* cambiar <rangoedad> por <observaciones tipo="rangoedad">
* cambiar <filiacion> por <observaciones tipo="filiacion">
* cambiar <sector_social> por <sector_condicion>
* falta <observaciones tipo="contexto">
* en pruebas no está guardando 
* cambiar <vinculo_estado> por <observaciones tipo='vinculo_estado'>
* cambiar <filiacion> por <observaciones tipo='filiacion'>
* modificar el DTD
* ampliar pruebas de regresión y verificación de DTD con casos que incluyan combatientes

**Comment by vtamara** [comment]
Caso de prueba:
![screencapture-181-143-184-115-2300-casos-162060-edita-2021-06-09-21_12_57](https://user-images.githubusercontent.com/701221/121453910-8a0f3900-c967-11eb-819c-f3492457aa73.png)

**Comment by vtamara** [comment]
```
<!-- Actos con Victimas Colectivas -->
       <!-- Combatientes -->
       <combatiente>
         <nombre>Pedro</nombre>
         <alias>Ramírez</alias>
         <edad>40</edad>
         <sexo>M</sexo>
         <profesion>SIN INFORMACIÓN</profesion>
         <rangoedad>SIN INFORMACIÓN</rangoedad>
         <filiacion>SIN INFORMACIÓN          </filiacion>
         <sector_social>SIN INFORMACIÓN</sector_social>
         <organizacion>PROFESIONAL              </organizacion>
         <organizacion_armada>SIN INFORMACIÓN</organizacion_armada>
         <vinculo_con_estado>SIN INFORMACIÓN</vinculo_con_estado>
         <resultado_agresion>MUERTO</resultado_agresion>
       </combatiente>
       <combatiente>
         <nombre>juan</nombre>
         <alias>perez</alias>
         <edad>30</edad>
         <sexo>M</sexo>
         <profesion>ABOGADO/A</profesion>
         <rangoedad>SIN INFORMACIÓN</rangoedad>
         <filiacion>AAA</filiacion>
         <sector_social>AMBIENTALISTA</sector_social>
         <organizacion>AMBIENTALISTA            </organizacion>
         <organizacion_armada>ACCU</organizacion_armada>
         <vinculo_con_estado>ALCALDIA</vinculo_con_estado>
         <resultado_agresion>MUERTO</resultado_agresion>
       </combatiente>
       <!-- Otros -->
       <observaciones tipo="grconfiabilidad"></observaciones>
```

**Comment by vtamara** [comment]
Al importar de nuevo, importa con errores (que no debería)
![SIVeL 2-0b14 9-6-2021 9-20-19 p- m-](https://user-images.githubusercontent.com/701221/121454503-86c87d00-c968-11eb-9c05-e410fdd70c1a.png)

 ```
En la tabla resultado agresión no exste 'MUERTO'. No se encuentra resagresion SIN INFORMACIÓN. En la tabla resultado agresión no exste 'MUERTO'. No se encuentra resagresion SIN INFORMACIÓN. 
```

**Comment by vtamara** [comment]
![screencapture-181-143-184-115-2300-casos-162061-edita-2021-06-09-21_24_05](https://user-images.githubusercontent.com/701221/121454789-0ce4c380-c969-11eb-893d-a580e4c7c102.png)
