### ISSUE TITLE
F-364 En sivel2 rama main, en formulario de lugarpreliminar no permite adjuntar KML [1]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#400]
Deja poner una nueva y remplazarla correctamente
![SIVeL 2-0b14 22-5-2021 9-23-09 a- m-](https://user-images.githubusercontent.com/701221/119229834-587d1d80-badf-11eb-8f28-d7a160439d63.png)

Pero al intentar descargar/abrir:
![Action Controller- Exception caught 22-5-2021 9-24-30 a- m-](https://user-images.githubusercontent.com/701221/119229888-86faf880-badf-11eb-8ed5-4f98776d2ada.png)

El URL que generó fue:
http://181.143.184.115:2300/181.143.184.115:2300/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhibkV5TldwbGFUbHZjV2hpYUdWNGNIbzJibWRtY0dreWEzWmpaUVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVpCaGRIUmhZMmh0Wlc1ME95Qm1hV3hsYm1GdFpUMGlRMkZ3ZEhWeVlTQmtaU0J3WVc1MFlXeHNZU0JrWlNBeU1ESXhMVEExTFRJd0lERXhMVEV5TFRVMkxuQnVaeUk3SUdacGJHVnVZVzFsS2oxVlZFWXRPQ2NuUTJGd2RIVnlZU1V5TUdSbEpUSXdjR0Z1ZEdGc2JHRWxNakJrWlNVeU1ESXdNakV0TURVdE1qQWxNakF4TVMweE1pMDFOaTV3Ym1jR093WlVPaEZqYjI1MFpXNTBYM1I1Y0dWSklnNXBiV0ZuWlM5d2JtY0dPd1pVT2hGelpYSjJhV05sWDI1aGJXVTZDbXh2WTJGcyIsImV4cCI6IjIwMjEtMDUtMjJUMTQ6Mjg6NDIuMjM0WiIsInB1ciI6ImJsb2Jfa2V5In19--7a96deea0f016ef726b0bc195289256bfe9464c6/Captura%20de%20pantalla%20de%202021-05-20%2011-12-56.png

**Comment by vtamara** [comment]
https://user-images.githubusercontent.com/701221/173621454-4a73c712-f9d1-4ca3-bd2b-1a292279cf4a.mp4

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/178770235-407d686f-7af3-4eb9-bb6e-61afa40127a4.MOV

**Comment by vtamara** [comment]
Si opera en aplicación de prueba apo214 pero no en sivel2 con variable de ambiente SIVEL2_DESAPARICION=1.  Apenas se intenta guardar el lugar de desaparición con KML aparece el fondo de un mensaje de alerta, pero sin texto:
![image](https://user-images.githubusercontent.com/701221/179049822-4113f78c-2d6d-4742-891e-5bc540cf227e.png)

**Comment by vtamara** [comment]
Arreglado con cambios recientes.
