### ISSUE TITLE
R-411 Completar F-394 [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#411]
cambiar elementos para coincidir con otros existentes y corregir otros problemas:
- [x] `<profesion>` debería ser `<ocupacion>`
- [x] cambiar `<rangoedad>` por `<observaciones tipo="rangoedad">`
- [x] cambiar `<filiacion>` por `<observaciones tipo="filiacion">`
- [x] cambiar `<sector_social>` por `<sector_condicion>` 
- [x] falta `<observaciones tipo="contexto">`
- [x] en pruebas no está guardando 
- [x] cambiar `<vinculo_estado>` por `<observaciones tipo='vinculo_estado'>`
- [x] cambiar `<filiacion>` por `<observaciones tipo='filiacion'>`
- [x] No está importando bien organización
- [x] modificar el DTD

**Comment by alejocruzrcc** [comment]
Al hacer estos cambios, se ha notado que las pruebas de regresión se estaban realizando con el dtd 097 y no con el 098 que es el que está establecido en este momento (la diferencia es la ubicación secundaria): Esto se actualizó!

Prueba al generar combatiente en un relato xrlat
![123372052-7f989600-d548-11eb-9658-0cff3d83145a](https://user-images.githubusercontent.com/12545631/125521478-921419a6-6002-47ba-b2fd-f4f3ee292f28.png)

**Comment by vtamara** [comment]
Se ve operando.
Falta cambiar versión de DTD y ampliar pruebas de regresión.
