### ISSUE TITLE
F-414 Arreglar falla con numero total de datos mostrados en gráfica. Debe ser igual que en mapa y contador [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#414]

**Comment by vtamara** [comment]
No se ve operando. Ver #415

**Comment by alejocruzrcc** [comment]
Al hacer estos cambios, se ha notado que las pruebas de regresión se estaban realizando con el dtd 097 y no con el 098 que es el que está establecido en este momento (la diferencia es la ubicación secundaria): Esto se actualizó!

Prueba al generar combatiente en un relato xrlat:
![Captura de pantalla de 2021-06-25 00-00-40](https://user-images.githubusercontent.com/12545631/123372052-7f989600-d548-11eb-9658-0cff3d83145a.png)

Se hicieron cambios en la importación de tipo observaciones en combatientes, similar a como se hace en victimas.

**Comment by vtamara** [comment]
Demasiado desgastante
