### ISSUE TITLE
F-418 Arreglar falla al importar relatos con combatientes [1]

### ISSUE THREAD

**Issue by alejocruzrcc** [pasosdeJesus/sivel2_gen#418]
Creditos a Cristian Llanos por detectar esta falla al improtar este conjuntos de casos.

**Comment by vtamara** [comment]
Avanza con #417

**Comment by vtamara** [comment]
Se importan los 19 casos del conjunto que presentaba problemas.

![Motor de SIVeL genérico 19-6-2021 11-04-56 a- m-](https://user-images.githubusercontent.com/701221/122648291-40a0b580-d0ee-11eb-8ce9-d4f0d00ad7c7.png)
