### ISSUE TITLE
R-427 Exportacíon a XRLAT debe exportar versión 0.99. Actualizar y ampliar pruebas con minitest de exportación e importación para que usen versión 0.99 del DTD y lo prueben completo con más casos de prueba [2] 

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#427]
Deben probar combatiente

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2021-07-28 01-30-26](https://user-images.githubusercontent.com/12545631/127274973-ae9b2403-cb3e-476c-a3f9-0f743c5c5df2.png)

![Captura de pantalla de 2021-07-28 01-27-02](https://user-images.githubusercontent.com/12545631/127274993-29f6f427-e5a0-4867-98a0-65b94893b44a.png)

**Comment by vtamara** [comment]
https://github.com/pasosdeJesus/sivel2_gen/pull/435/

**Comment by vtamara** [comment]
Exporte un caso y sigue apareciendo que usa el DTD 0.98:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE relatos SYSTEM "https://sincodh.pasosdejesus.org/relatos/relatos-098.dtd">
<relatos>
     <relato>
```

**Comment by vtamara** [comment]
importa un caso que exporté, no importó bien el rango de edad.

El original tenía:
![SIVeL 2-0b15 30-7-2021 6-18-48 a- m-](https://user-images.githubusercontent.com/701221/127645648-f2447f2d-7dbe-4a4f-8bfb-1289bdf15aee.png)

En relato se ve bien:
```
 <observaciones tipo="rangoedad">DE 61 EN ADELANTE</observaciones> 
```

Pero al importar no queda:
![SIVeL 2-0b15 30-7-2021 6-20-15 a- m-](https://user-images.githubusercontent.com/701221/127645735-83e411d0-f353-43ca-b013-bdd2fbd2fcd7.png)

**Comment by vtamara** [comment]
Corren bien pruebas con minitest ampliadas.  Parecería que no están verificando DTD y alguna prueba debería hacerlo.

**Comment by alejocruzrcc** [comment]
prueba desde main si aparece dtd 99
![Captura de pantalla de 2021-07-31 13-26-09](https://user-images.githubusercontent.com/12545631/127749259-a11171cf-3a1e-4598-b68f-a05fb7e98392.png)

**Comment by vtamara** [comment]
Gracias, tiene razón ya exporta con 099.
Para el problema con rango de edad quedó una incidencia aparte #438
