### ISSUE TITLE
R-430 En menú Casos->Validaciones agregar filtro por etiqueta (por ejemplo para validar actualizaciones) (Noviembre) [1]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#430]

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2021-11-09 19-36-07](https://user-images.githubusercontent.com/12545631/141028224-c60d72c4-a94c-46ba-a69c-e2a5d4291a58.png)

**Comment by vtamara** [comment]
No está operando.
Aunque permite elegir una etiqueta, después la validación se hace sobre todos los casos y debería ser sólo sobre los casos que tengan la etiqueta:

* Sin etiqueta:
![image](https://user-images.githubusercontent.com/701221/141387157-28c98073-5ecf-4259-9be5-7ce7d6d69038.png)

* Con etiquetea (debería haber 0 casos):
![ScreenShot Tool -20211111191458](https://user-images.githubusercontent.com/701221/141387123-5bdb9d1b-880c-4377-b6bf-93275c486aeb.png)

**Comment by vtamara** [comment]
Operó
