### ISSUE TITLE
R-431 En formulario de casos, que cuando se agreguen víctimas con nombre N y apellido N aparezca una numeración automática de NNs tanto en el la pestaña de víctimas como en actos [4]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#431]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-26 15-08-46](https://user-images.githubusercontent.com/10052756/127052225-9213d628-3291-4b04-ac08-cb35561e8731.png) No se ve la numeración

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/127715238-e424e79b-bc2f-43ff-9934-89ce63ca02e0.MOV

**Comment by vtamara** [comment]
En el vídeo y al probar se ve que cuando escribe en la pestaña víctima nombre N y apellido N el título de la víctima no cambia y sigue diciedo "PERSONA IDENTIFICADA". 
O despues de guardar y volver a editar si se pone nombre y apellido a una persona no identificada, sigue diciendo persona no identificada y sólo actualiza tras guardar y volver a edidtar.

**Comment by alejocruzrcc** [comment]
Más dinámico:
https://user-images.githubusercontent.com/12545631/130128318-a16572f6-55e9-418c-899e-28863c6bd32b.MOV

**Comment by vtamara** [comment]
Cuando se inicia una nueva víctima comienza con PERSONA IDENTIFICADA pero debería comenzar con PERSONA NO IDENTIFICADA
![Motor de SIVeL genérico 23-8-2021 12-49-59 p- m-](https://user-images.githubusercontent.com/701221/130493549-ac3510ce-4f68-4a85-bb60-279a360875e0.png)

**Comment by pmartinez5** [comment]
[
![FireShot Capture 190 - SIVeL 2 0b17 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/142349894-71318e71-49c9-48fc-be2c-29ce1c3af985.png)
](url)
[
![FireShot Capture 191 - SIVeL 2 0b17 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/142349979-75480ea4-207d-4476-b82e-bd29e9edaf00.png)
](url)
