### ISSUE TITLE
R-434 Presentar listado de presuntos responsables como árbol donde se vea estructura papa-hijos [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#434]

**Comment by vtamara** [comment]
En menú se ve dede Administrar
![Uploading SIVeL 2-0b15 28-7-2021 4-48-17 a- m-.png…]()

**Comment by vtamara** [comment]
Una vez se elige los presuntos responsables habilitados se presenta como árbol, con la estructura dada por el campo Subestructura de:

![screencapture-181-143-184-115-2300-admin-presponsables-arbol-2021-07-28-04_48_54](https://user-images.githubusercontent.com/701221/127302127-474aa5bc-9f4d-4c62-a391-180bff017414.png)

**Comment by pmartinez5** [comment]
[
![FireShot Capture 176 - SIVeL 2 0b17 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/142350808-b58bb75b-e935-42da-b125-177bec0401c0.png)
](url)
