### ISSUE TITLE
F-438 Problemas al exportar e importar rangos de edad de víctimas y combatientes  [0.4]

### ISSUE THREAD

**Issue by alejocruzrcc** [pasosdeJesus/sivel2_gen#438]

**Comment by vtamara** [comment]
En el comprimido adjunto hay un relato
[ejrelatorangos.zip](https://github.com/pasosdeJesus/sivel2_gen/files/6981879/ejrelatorangos.zip)

Que tiene varias víctimas y un combatiente, todos con algún rango de edad especificado.

Por ejemplo la víctima 1 tiene:
``` 
<observaciones tipo="rangoedad">R3</observaciones>
```

Mientras que le combatiente tiene:
```
<observaciones tipo="rangoedad">De 26 a 45 Años</observaciones>
```

El primer error es que debería emplearse la misma convencińo para víctimas individuales como para combatientes al exportar.  Es mejor convención "De 26 a 45 Años" que "R3"


Y lo segundo es que al importar, si importa el rango de edad de las víctimas:
![Motor de SIVeL genérico 13-8-2021 5-59-03 a- m-](https://user-images.githubusercontent.com/701221/129347395-00275b3d-1744-4c1b-8b9f-b7fb8fa25567.png)


Pero no el de combatiente:
![Motor de SIVeL genérico 13-8-2021 5-59-54 a- m-](https://user-images.githubusercontent.com/701221/129347474-f29f01cf-5e43-41cb-b6c7-99ba61ee41e4.png)

**Comment by vtamara** [comment]
Sivel2Gen::Rangoedad tiene campos redundantes `nombre` y `rango`.

Por ejemplo para el `id`1, `nombre` es `R1` y `rango` es `De 0 a 15 Años`.

Se trata de un problema histórico, que arreglaremos (ver ), pero para esta incidencia por lo pronto para exportar e importar por favor usar el campo `rango` en lugar de `nombre`.

**Comment by alejocruzrcc** [comment]
arreglado en https://github.com/pasosdeJesus/sivel2_gen/pull/446

**Comment by vtamara** [comment]
Resuelto
