### ISSUE TITLE
R-485 Mantenimiento a wordpress Alonso de Sandoval: revisión de copias de respaldo,  verificación de sumas de chequeo de seguridad, probar en sitio de desarrollo quitar dependencia de plugins obsoletos que no operan con PHP 8 (Octubre-I) [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#485]

**Comment by alejocruzrcc** [comment]
No se hacen copias de respaldo a diario
 Captura tomada el 2 de Noviemre de 2021
 
![Captura de pantalla de 2021-11-02 18-02-40](https://user-images.githubusercontent.com/12545631/139969842-4c0a23dc-9a19-45f8-bb19-2fc65fe9e8c8.png)

**Comment by alejocruzrcc** [comment]
Verificación de base de datos
![Captura de pantalla de 2021-10-26 11-07-05](https://user-images.githubusercontent.com/12545631/139969958-bf63783c-ac2c-419d-acf4-1825c91257d3.png)

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2021-11-03 21-51-41](https://user-images.githubusercontent.com/12545631/140250237-1b9cfb24-eb54-4a40-adc1-c34491e291aa.png)
![Captura de pantalla de 2021-11-03 21-55-08](https://user-images.githubusercontent.com/12545631/140250247-2633ca95-03d1-4179-b933-207682fc7087.png)

**Comment by alejocruzrcc** [comment]
Actualización de plugins:
![Captura de pantalla de 2021-11-03 21-57-05](https://user-images.githubusercontent.com/12545631/140250359-c3470a24-d31d-483a-911c-3da36171280a.png)

**Comment by vtamara** [comment]
Realizado y documentado en GLPI.
