### ISSUE TITLE
R-534 Con un programa por agregar en bin de sivel2 rama sivel2.0 extraer todas las rutas de sivel2.0 (bin/rails routes) y formatearlas para ponerlas en este incidente, con chulos para las que ya tienen prueba de control de acceso y casilla en blanco para las que no tienen aún (Noviembre) [2,6]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#534]

**Comment by vtamara** [comment]
Implementado con https://github.com/pasosdeJesus/sivel2/pull/64

**Comment by vtamara** [comment]
Evidenciar que todas las rutas han sido cubiertas, por ejemplo copiar todas las rutas de bin/rails routes y que tengan chulo las que ya tengan pruebas de control de acceso y documentación completas.

**Comment by vtamara** [comment]
- [ ] `/casos`

**Comment by alejocruzrcc** [comment]
- [ ]  /sivel2/sivel2/usuarios/sign_in(.:format)       
- [ ]  /sivel2/sivel2/usuarios/sign_in(.:format)                                                                                                          
- [ ]  /sivel2/usuarios/sign_in(.:format) 
- [ ]  /sivel2/usuarios/sign_out(.:format)
- [ ]  /sivel2/usuarios/unlock/new(.:format)                       
- [ ]  /sivel2/usuarios/unlock(.:format)  
- [ ]  /sivel2/usuarios/unlock(.:format)   
- [ ]  /sivel2/usuarios/edit(.:format)         
- [ ]  /sivel2/usuarios/:id(.:format)              
- [ ]  /sivel2/usuarios(.:format)

**Comment by vtamara** [comment]
Cerrado con https://github.com/pasosdeJesus/sivel2/pull/66
