### ISSUE TITLE
R-535 Dejar usable el formulario de lugar de desaparición y probarlo con casos [4] (Noviembre)

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#535]

**Comment by alejocruzrcc** [comment]
Fallas encontradas:
1. Al agregar asistente se sale del formulario de lugar preliminar.
2. Al agregar asistente no quedan en blanco los campos
3. No funciona drag and drop en el listado de asistentes
4. no guarda posicion  de lista despues de guardar y editar
5. No funciona Best_in_place para editar

Actualizaciones e investigación en: Hotwire, action cable, stimulus , turbo, actas_as_list, sortablejs, best_inplace

**Comment by vtamara** [comment]
Es más usable.
