### ISSUE TITLE
F-545 Que funcionen bien gráfica de victimizaciones individuales y de actos individuales en sivel2 --así como funcionan en sivel2_gen (Noviembre) [0,4]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#545]

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2021-11-11 03-01-36](https://user-images.githubusercontent.com/12545631/141260596-ffba5e94-749c-4068-9272-868074409d52.png)
 En sivel2 si esta cargando correctamente la gráfica. Puede ser que tengas la base de datos vacía o que me muestres especificamente como reproducir el error.

**Comment by vtamara** [comment]
Al elegir "Desagregar por" "Departamento":
1. Sexo sale a la derecha pero debería salir abajo remplazando lo que era departamento con opciones de selección múltiple con chosen
2. Genera error:
![image](https://user-images.githubusercontent.com/701221/144327489-2b7a129f-94c2-49ce-96a9-ed7b3a5d6bf1.png)

**Comment by vtamara** [comment]
Reimplementada
