### ISSUE TITLE
R-546 Mantenimiento preventivo a alonsodesandoval (Noviembre) [0,8]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#546]

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2021-11-30 23-44-16](https://user-images.githubusercontent.com/12545631/144173495-cba8d441-2ef2-4f1b-8a68-600b4cb930a2.png)
![Captura de pantalla de 2021-11-30 23-42-49](https://user-images.githubusercontent.com/12545631/144173499-e0289236-1482-4273-9aa8-344a174f9a75.png)
![Captura de pantalla de 2021-11-30 23-41-09](https://user-images.githubusercontent.com/12545631/144173500-f5874f6d-d904-4afe-abba-17d31e243a72.png)
![Captura de pantalla de 2021-11-30 23-38-14](https://user-images.githubusercontent.com/12545631/144173503-e2729113-f6ec-4e1d-af06-0b396b704f1a.png)
![Captura de pantalla de 2021-11-30 23-34-45](https://user-images.githubusercontent.com/12545631/144173508-3f277b21-98a0-4fcd-a612-abd7d4374d07.png)
![Captura de pantalla de 2021-11-30 23-27-02](https://user-images.githubusercontent.com/12545631/144173510-2cd9210b-e6e9-4a5d-b61b-7cd5c6ed35c3.png)
![Captura de pantalla de 2021-11-30 23-22-50](https://user-images.githubusercontent.com/12545631/144173512-7c2f49b0-06e0-4a10-9cdc-9c9353921dde.png)
![Captura de pantalla de 2021-11-30 22-57-56](https://user-images.githubusercontent.com/12545631/144173514-a7007781-e6c1-44f4-aa9a-a82a00389bb8.png)
