### ISSUE TITLE
R-566 Actualiza DIVIPOLA  a la versión 2020 

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#566]

**Comment by pmartinez5** [comment]
[
![FireShot Capture 172 - SIVeL 2 0b17 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/142351053-7932a6a9-7d79-4ed3-9e45-1adad36baf6e.png)
](url)

**Comment by vtamara** [comment]
Implementado
