### ISSUE TITLE
R-569 Comparar listado de veredas del DANE 2017 con las depuradas manualmente de Banco de Datos en 2018 con financiación de Sheffield [4]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#569]

**Comment by vtamara** [comment]
Se encuentran 2 departamentos con nombre errado: QUINDIO Y BOGOTÁ D.C.  Son QUINDÍO Y BOGOTÁ, D.C.

Se encuentra 19 municipio con nombre errado:

| Dice | Debería Decir |
| TOLIMA / SALDAÑA | TOLIMA /  |
| TOLIMA / MARIQUITA | TOLIMA /  |
| TOLIMA / ARMERO (GUAYABAL) | TOLIMA /  |
| VALLE DEL CAUCA / RIOFRÍO | VALLE DEL CAUCA /  |
| VALLE DEL CAUCA / TULUA | VALLE DEL CAUCA /  |
| VALLE DEL CAUCA / CALIMA (DARIEN) | VALLE DEL CAUCA /  |
| VALLE DEL CAUCA / JAMUNDI | VALLE DEL CAUCA /  |
| VALLE DEL CAUCA / ANDALUCÍA | VALLE DEL CAUCA /  |
| ANTIOQUIA / SAN VICENTE | ANTIOQUIA /  |
| ANTIOQUIA / SANTUARIO | ANTIOQUIA /  |
| ANTIOQUIA / SAN ANDRÉS | ANTIOQUIA /  |
| ANTIOQUIA / BOLÍVAR (CIUDAD BOLÍVAR) | ANTIOQUIA /  |
| ANTIOQUIA / SANTAFÉ DE ANTIOQUIA | ANTIOQUIA /  |
| ANTIOQUIA / CARMEN DE VIBORAL | ANTIOQUIA /  |
| ANTIOQUIA / DON MATÍAS | ANTIOQUIA /  |
| ANTIOQUIA / SAN PEDRO | ANTIOQUIA /  |
| CUNDINAMARCA / GUAYABAL DE SIQUIMA | CUNDINAMARCA /  |
| CAUCA / PATÍA (EL BORDO) | CAUCA /  |
| CAUCA / SOTARA (PAISPAMBA) | CAUCA /  |
| CAUCA / PURACE (COCONUCO) | CAUCA /  |
| CAUCA / PÁEZ (BELALCAZAR) | CAUCA /  |
| CAUCA / null | CAUCA /  |
| PUTUMAYO / VALLE DEL GUAMUEZ (LA HORMIGA) | PUTUMAYO /  |
| SANTANDER / LEBRÍJA | SANTANDER /  |
| SANTANDER / null | SANTANDER /  |
| CHOCÓ / ALTO BAUDO (PIE DE PATO) | CHOCÓ /  |
| CHOCÓ / QUIBDO | CHOCÓ /  |
| BOGOTÁ, D.C. / BOGOTÁ | BOGOTÁ, D.C. /  |
| SUCRE / TOLU | SUCRE /  |
| SUCRE / COLOSÓ (RICAURTE) | SUCRE /  |
| NARIÑO / TUMACO | NARIÑO /  |
| NARIÑO / LOS ANDES (SOTOMAYOR) | NARIÑO /  |
| NARIÑO / ROBERTO PAYÁN (SAN JOSÉ) | NARIÑO /  |
| NARIÑO / ALBAN (SAN JOSÉ) | NARIÑO /  |
| CALDAS / null | CALDAS /  |
| ARAUCA / null | ARAUCA /  |
| CESAR / CURUMANI | CESAR /  |
| CESAR / null | CESAR /  |
| BOYACÁ / GÜICÁN | BOYACÁ /  |
| BOLÍVAR / TIQUISIO (PUERTO RICO) | BOLÍVAR /  |
| BOLÍVAR / CARTAGENA | BOLÍVAR /  |
| VICHADA / null | VICHADA /  |
| NORTE DE SANTANDER / CACHIRÁ | NORTE DE SANTANDER /  |
| MAGDALENA / ARIGUANÍ (EL DIFICÍL) | MAGDALENA /  |

**Comment by vtamara** [comment]
Lo desarrollado para la comparación fue:
https://gitlab.com/vtamara/watergate/-/commit/74165f7d56f8e61e11c1ab89b6526c39b70205cd

**Comment by pmartinez5** [comment]
Se probo TOLIMA / MARIQUITA
ANTIOQUIA / BOLÍVAR (CIUDAD BOLÍVAR)
--


[
![Dibujo sin título (1)](https://user-images.githubusercontent.com/61369119/156700955-f9034868-ba08-4802-8abf-b6a9712b782a.jpg)
](url)

**Comment by pmartinez5** [comment]
No funcionan

**Comment by pmartinez5** [comment]
[](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título](https://user-images.githubusercontent.com/61369119/156701784-7e240546-e723-45e8-be9f-acd743e708a5.jpg)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (1)](https://user-images.githubusercontent.com/61369119/156702176-54911a8e-34b5-4510-b5ee-df4618948878.jpg)
](url)

**Comment by pmartinez5** [comment]
[](url)

**Comment by pmartinez5** [comment]
![Dibujo sin título (2)](https://user-images.githubusercontent.com/61369119/156702560-e9dd0a0e-19d9-413c-b552-951d009e1bd7.jpg)
