### ISSUE TITLE
R-600 En mapa de calor agregar filtro de selección múltiple por categoría [2] 

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#600]

**Comment by pmartinez5** [comment]
[
![FireShot Capture 396 - SIVeL 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146629601-fe8e5f6a-e9a4-4943-bba1-44619dae88d4.png)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título](https://user-images.githubusercontent.com/61369119/146629638-fc8c7b19-f6d9-46d0-a6d6-10e1e5a94a55.png)
](url)
