### ISSUE TITLE
R-601 En mapa de victimizaciones agregar filtro por categoría proveniente de SIADDHH pero convertir jQuery a Javascript puro [3]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#601]

**Comment by vtamara** [comment]
Nos ha servido:
https://tutorialzine.com/2014/06/10-tips-for-writing-javascript-without-jquery
https://drafts.csswg.org/selectors/

# Selectores

En general pueden cambiarse selectores de la forma j = $("input[name='x']") por j = document.querySelector("input[name='x']")

**Comment by vtamara** [comment]
El código proveniente de SIADDHH inicial era:

![_home_vtamara_Downloads_Romanos-1 html](https://user-images.githubusercontent.com/701221/144831630-71878931-83ce-439c-b5cb-0478fea44025.png)

**Comment by vtamara** [comment]
![screencapture-nuevo-nocheyniebla-org-3300-sivel2-1-mapadep-victimizaciones-2021-12-07-06_13_27](https://user-images.githubusercontent.com/701221/145019308-6e4b262a-b2f5-48bb-883a-5ec913bd1717.png)

**Comment by vtamara** [comment]
Nos parece que el movimiento de no usar jquery proviene del comite que desarrolla Javascript. 

Es positivo que Javascript esté incorporando buenas caracteristicas de jquery como `querySelector` cuyo lenguaje de selectores al parecer es inspirado en jquery.    En la medida que el lenguaje mismo permita con facilidad hacer lo mismo que la librería, vale la pena convertir para ganar velocidad.

Sin embargo nos parece que se está apresurando el cambio cuando (1) no hay remplazo para todo y (2) el cambio tiende a aumentar tamaño de las fuentes (aunque bootstrap 5 que no usa jquery es más pequeño que sus predecesores).  

En particular de lo que tenemos hasta ahora no encontramos remplazo para:

1. Mecanismo de eventos modular de jquery, en particular del estilo `document.on('change', '#id_de_elemento_futuro'`.  El posible cambio con `document.addEventListener('change', function(e)` no es tan modular y no funciona con plugins de jQuery --como chosen-- que usan el mecanismo de eventos de jQuery.
2. Autocompletación en cajas de texto con `jquery-ui`.  Aunque por lo visto datalist ha sido incorporado en HTML para esto.  Nos parece que los navegadores recientes se están bloqueando más con la autocompletación de jquery-ui (ver ).
3. Librería equivalente a `chosen` para cuadro de selección mejorados. Las comparaciones que hemos hecho con otros como select2 (que también depende de jquery) nos muestran que no tienen todas las características de chosen.
4. Librería equivalente a `bootstrap-datepicker` para selector de fechas. No hemos encontrado uno en javascript puro con todas las características.  Parece que los navegadores prefieren que se use el control nativo de HTML.
5. Librería equivalente a `cocoon` para formulario anidados más dinámicos.  Hemos empezado a experimentar con hotwire para esto.

Todo esto se puede probar en el formulario de organización social de la aplicación de prueba de sip.

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (1)](https://user-images.githubusercontent.com/61369119/146631159-c3cbf9fa-cff0-4690-8936-9be8161509fb.png)
](url)
