### ISSUE TITLE
R-602 En gráfica de victimizaciones individuales permitir elegir color y el tipo de gráfica: barras verticales, barras horizontales, líneas, áreas,  torta, dona [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#602]

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (2)](https://user-images.githubusercontent.com/61369119/146630985-e334a9e1-3f0d-46dd-87c8-aeccd67a11ce.png)
](url)

**Comment by pmartinez5** [comment]
[
![FireShot Capture 398 - SIVeL 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146630998-87d97421-2d9e-4e5d-a859-07112914a5ea.png)
](url)
[
![FireShot Capture 400 - SIVeL 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146631003-99d08275-9548-40f3-82bd-2c0dda84b9a8.png)
](url)
