### ISSUE TITLE
R-603 En conteo de victimizaciones individual usar control de categoría proveniente de SIADDHH pero mejorarlo integrando con tipo de violencia y excluir categorías repetidas. Reusar en mapa de victimizaciones [1].

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#603]

**Comment by pmartinez5** [comment]
[
![Dibujo sin título](https://user-images.githubusercontent.com/61369119/146630494-525d0ae9-2893-4fde-a450-82efe8fcc825.png)
](url)

**Comment by pmartinez5** [comment]
[
![Dibujo sin título (1)](https://user-images.githubusercontent.com/61369119/146630660-c0f5c73c-dc46-4eed-9e69-26cd055d78f4.png)
](url)
