### ISSUE TITLE
F-606 Un usuario con Rol Operador y Grupo observador de casos no debería poder editar/actualizar un registro de Bitácora [0,4]

### ISSUE THREAD

**Issue by alejocruzrcc** [pasosdeJesus/sivel2_gen#606]
![Captura de pantalla de 2021-12-07 00-16-21](https://user-images.githubusercontent.com/12545631/145059235-39cdc8cf-985f-462d-8d7f-541455e554d7.png)

**Comment by alejocruzrcc** [comment]
también un usuario operador sin ningun grupo

**Comment by vtamara** [comment]
Cerrado con #607
