### ISSUE TITLE
R-611 En gráfica de victimizaciones individuales limitar cada tipo de gráfica (excepto líneas) al número de daatos que podrían graficar en aprox. 10 segundos  [1]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#611]

**Comment by vtamara** [comment]
* Barras horizontales y verticales: 2000.  Pero las horizontales no son legibles después de unas cuantas porque el alto de la gráfica es pequeño (ver https://github.com/pasosdeJesus/siaddhh/issues/86)
* Área: 3000
* Torta y Dona: ~500 pero nos parece que no tiene mucho sentido para más de 20.
* Líneas: ~10.000 pero lo dejamos sin limitación porque debe depender de características del equipo y navegador.

**Comment by pmartinez5** [comment]
[
![FireShot Capture 397 - SIVeL 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146629662-5c393167-e14e-411e-8feb-b0ce05650248.png)
](url)
[
![FireShot Capture 398 - SIVeL 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146629666-ebafffe6-e076-482b-8154-ae2e03d8908b.png)
](url)
[
![FireShot Capture 400 - SIVeL 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146629671-075baf2c-cdfa-4e15-bf00-74ba7b4f7df8.png)
](url)
[
![FireShot Capture 401 - SIVeL 2 1a1 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/146629680-56b22f1a-0adf-4d5c-bcd4-fbd2916b3879.png)
](url)
