### ISSUE TITLE
R-619 Mantenimiento a alonsodesandoval en Diciembre [0,8]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#619]

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2021-12-30 17-17-05](https://user-images.githubusercontent.com/12545631/147798434-6e3a9ee0-1a14-4048-9398-66607a513f93.png)
![Captura de pantalla de 2021-12-30 17-15-20](https://user-images.githubusercontent.com/12545631/147798435-c21ddbcb-7e3b-4bab-9cc7-200f73996824.png)
![Captura de pantalla de 2021-12-30 17-13-11](https://user-images.githubusercontent.com/12545631/147798436-d56801b0-5bf7-4ce1-a30c-55d0e7e11eea.png)
![Captura de pantalla de 2021-12-30 17-04-48](https://user-images.githubusercontent.com/12545631/147798437-955a574f-f536-4c5c-991e-97246fad76ac.png)
