### ISSUE TITLE
F-624 En rama sivel2.0 al filtrar en reportes y conteos>> victimas y casos>> lesionado vps genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#624]
![Captura de pantalla de 2021-12-21 20-19-55](https://user-images.githubusercontent.com/10052756/147019658-5a3f1e44-6cd3-4b07-a8ca-cffcac75915c.png)

**Comment by vtamara** [comment]
No reproducible. El mensaje de error del pantallazo sugiere que la prueba coincidio con un reinicio del servicio.
