### ISSUE TITLE
F-638 En tablas basicas >> regiones al llenar los campos genera error de validación en sivel2.1 [0,2]

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#638]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2022-01-06 17-40-06](https://user-images.githubusercontent.com/10052756/148596976-fbf1a01e-323f-4a87-99eb-a56b0eea1fff.png)

**Comment by vtamara** [comment]
> También al tratar de eliminar una región genera error de validación: ![Captura de pantalla de 2022-02-01 11-26-28](https://user-images.githubusercontent.com/12545631/152008733-de36df09-bae8-4431-b6a0-ba67aa19af58.png)

Eso no es error sino característica.
