### ISSUE TITLE
F-640 Al filtrar por Reportes y conteos >> victimas y casos por heridos genera error 

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#640]
![Captura de pantalla de 2022-01-08 10-27-32](https://user-images.githubusercontent.com/10052756/148650069-cd0fc5ec-d123-4676-ae1a-2981cb48e35a.png)
![Captura de pantalla de 2022-01-08 10-34-59](https://user-images.githubusercontent.com/10052756/148650191-cd62bffa-b046-4e16-a1f0-0f5308490d00.png)

**Comment by vtamara** [comment]
No se ha podido reproducir en rama reciente, favor especificar pasos.

**Comment by BlancaInesAcosta** [comment]
Ya esta funcionando
