### ISSUE TITLE
R-654 Refactorizar control de autocompletación iniciado para JRS-Colombia y usarlo en formulario de caso (víctima individual y víctima colectiva)

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#654]

**Comment by pmartinez5** [comment]
Prueba Autocompletaciòn en formulario caso victima individual
[
![Captura de pantalla_2022-01-24_12-49-53](https://user-images.githubusercontent.com/61369119/150837659-43b3bcfc-2387-4d34-8e3e-adc829e13270.png)
](url)
[
![FireShot Capture 475 - SIVeL 2 0 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/150837681-6fcff348-5479-4f9c-8cc5-9f0c56c981d6.png)
](url)

**Comment by pmartinez5** [comment]
Prueba en formulario caso victimas
[
![Dibujo sin título](https://user-images.githubusercontent.com/61369119/150843491-d70760ea-1b4e-4d17-9aa9-eb7ce0acb50c.jpg)
](url)
[
![Dibujo sin título](https://user-images.githubusercontent.com/61369119/150843038-d667c5b5-c355-4f22-a0e9-136ed7810e73.png)
](url)

**Comment by pmartinez5** [comment]
[
![Uploading FireShot Capture 481 - SIVeL 2.0 - rbd.nocheyniebla.org.png…]()
](url)

**Comment by pmartinez5** [comment]
[
![FireShot Capture 481 - SIVeL 2 0 - rbd nocheyniebla org](https://user-images.githubusercontent.com/61369119/150849149-c7b73a57-1c88-493a-a201-b724dc17c755.png)
](url)
