### ISSUE TITLE
F-656 Ruta personas/:id/fichaimp dañada: The action 'fichaimp' could not be found for Sip::PersonasController

### ISSUE THREAD

**Issue by alejocruzrcc** [pasosdeJesus/sivel2_gen#656]
![Captura de pantalla de 2022-01-28 00-00-43](https://user-images.githubusercontent.com/12545631/151490074-986325c5-a674-46df-a253-3920982ff23f.png)

**Comment by vtamara** [comment]
No prioritaria.
