### ISSUE TITLE
R-669 En formulario de lugares de disposición que los campos de autocompletación de personas usen nuevo control de autocompletación --como el de pestaña víctima en formulario caso [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#669]

**Comment by vtamara** [comment]
Como referencia se puede usar https://github.com/pasosdeJesus/sivel2_gen/issues/654

**Comment by vtamara** [comment]
Tras propuesta salen 2 controles de autocompletación:
![probaut](https://user-images.githubusercontent.com/701221/161117556-7ce97b80-b6c7-4e8b-9e33-195eb47cd7a3.png)

El de arriba es el nuevo con `datalist`

El de abajo es el que había con jquery-ui que debe deshabilitarse.

**Comment by vtamara** [comment]
No autocompleta en personas inhumadas:
![image](https://user-images.githubusercontent.com/701221/173626340-540f6fcc-9269-42d1-8cf6-cbab09fbb20c.png)

No autocompleta en otras fuentes:
![image](https://user-images.githubusercontent.com/701221/173626461-8184c83c-ef3e-4d26-92a2-847a4966f797.png)

Al guardar aparece fondo de error pero no mensaje, así que no se puede saber por que no guarda:
![screencapture-nuevo-nocheyniebla-org-2300-apo214-lugarespreliminares-1-2022-06-14-11_18_39](https://user-images.githubusercontent.com/701221/173626684-8d00814c-ec95-44ed-bfb4-3b30557eb5cb.png)

**Comment by vtamara** [comment]
Este problema ocurre tanto apo214 como en sivel2 con variable SIVEL2_DESPLAZAMIENTO

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/179895187-af8f9a90-5aaa-48dd-bc45-f4168af3f91e.MOV

**Comment by alejocruzrcc** [comment]
> Estos problemas ocurren tanto en
> 
> * apo214 como en
> * sivel2 con variable de ambiente SIVEL2_DESPLAZAMIENTO=1

Querrás decir SIVEL"_DESAPARICION=1 ?

**Comment by vtamara** [comment]
> > Estos problemas ocurren tanto en
> > 
> > * apo214 como en
> > * sivel2 con variable de ambiente SIVEL2_DESPLAZAMIENTO=1
> 
> Querrás decir DESAPARICION=1 ?

Correcto corregido. Gracias

**Comment by vtamara** [comment]
Propuesta de solución con https://github.com/pasosdeJesus/apo214/pull/67 que
* Se ve operando en apo214
* No opera en sivel2

**Comment by vtamara** [comment]
Implementado para apo214 con https://github.com/pasosdeJesus/apo214/pull/67
Falta que opere en sivel2
