### ISSUE TITLE
R-681 En conteo general de victimizaciones añadir filtro por etiqueta (para filtrar por revista) [1,6]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#681]

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2022-04-22 09-46-05](https://user-images.githubusercontent.com/12545631/164738368-81ca8165-9747-4561-a953-081150a49cc3.png)

Ejemplo de 3 casos que hay, uno tiene una etiqueta:
![Captura de pantalla de 2022-04-22 09-44-12](https://user-images.githubusercontent.com/12545631/164738509-7e889983-3b08-4272-9b11-563bef9c5288.png)

![Captura de pantalla de 2022-04-22 09-44-29](https://user-images.githubusercontent.com/12545631/164738683-65a7821c-f0ea-4fa8-9bf7-885bc7866651.png)

Antes del filtro:
![Captura de pantalla de 2022-04-22 09-45-47](https://user-images.githubusercontent.com/12545631/164738753-25e88d82-8014-4ed1-b0c3-b0738d8447fd.png)
Desppues del filtro:
![Captura de pantalla de 2022-04-22 09-46-17](https://user-images.githubusercontent.com/12545631/164738813-29cdf8e6-7c6a-4927-9227-f7dddbc69269.png)

**Comment by vtamara** [comment]
Cerrado con #710
