### ISSUE TITLE
R-682 En listado de víctimas y casos agregar filtro por etiqueta en el caso (para filtrar por revista) [3]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#682]

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2022-04-22 10-03-01](https://user-images.githubusercontent.com/12545631/164741475-1bdc758f-a573-4bb6-a721-d6b2f91e1b29.png)

Despues del filtro.
![Captura de pantalla de 2022-04-22 10-03-25](https://user-images.githubusercontent.com/12545631/164741586-7d4da67f-79fb-4288-994b-1218311e715b.png)

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/166116183-85518374-2e1f-44c0-9546-529bad24dd77.MOV
