### ISSUE TITLE
R-684 Al guardar un caso validar que no tenga ubicaciones sin departamento [0,6]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#685]
![image](https://user-images.githubusercontent.com/701221/157759849-2468aff2-3faa-4245-b709-57392e4598a1.png)

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2022-04-24 20-53-54](https://user-images.githubusercontent.com/12545631/165008271-06da29a4-6c9f-41ca-9aba-61b474965b2f.png)

**Comment by vtamara** [comment]
Implementado con https://github.com/pasosdeJesus/sivel2_gen/pull/718
Arreglado con https://github.com/pasosdeJesus/sivel2_gen/commit/f760de5360907a3f894bcb0205f25211bcec8a11
