### ISSUE TITLE
F-705 Un usuario con el rol de operador del grupo de analista de casos no puede ni crear ni cambiar nada en un caso

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#705]
![Captura de pantalla de 2022-03-31 09-27-31](https://user-images.githubusercontent.com/10052756/161079719-b0432839-967c-4609-8fd5-75848d7527ab.png)
![Captura de pantalla de 2022-03-31 09-28-48](https://user-images.githubusercontent.com/10052756/161079720-34917206-282b-4e2f-81d4-fd798f2e7dac.png)

**Comment by vtamara** [comment]
Aquí  no hay falla en el software sino en la configuración del sitio donde está probando, porque el id del grupo Analista de Casos es 103  y el de Observador es 102.

El id del grupo Analista de Casos debe ser 20 y el de Observador de Casos 21.

Por favor corrija en el sitio donde está probando.
