### ISSUE TITLE
R-717 En rama sexoel, garantizar que en un relato el sexo sea siempre "M" (masculino) o "F" (femenino) o "S" (sin información).   Si un sistema tiene la convención "H" (hombre), "M" (mujer), "S" (Sin información) homologar al exportar y al importar (ver #481). Inicialmente soportar sólo los trios (S,F,M) y (S,M,H) y probar extensivamente [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#717]

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/178770522-dbecb516-44a5-4fe3-97f3-c046fe6c8434.MOV

**Comment by vtamara** [comment]
Asegurar probar (preferible con minitest):
1. Valido MFS a HMS
* Sistema al que se importa usa formato Hombre-Mujer-Sin Información. 
* Sistema del cual se exportó la información usa formato Masculino-Femenino-Sin Información
* Al importa se elige correctamente Masculino-Femenino-Sin Información y en el sistema destino lo que era Masculino queda como Hombre, Femenino como Mujer y Sin Información como Sin Información

2. Valido HMS a MFS 
* Sistema al que se importa usa formato Masculino-Femenino-Sin Información
* Sistema del cual se exportó la información usa formato Hombre-Mujer-Sin Información
* Al importar se elige correctamente Hombre-Mujer-Sin Información y en el sistema destino lo que era Hombre queda Masculino, lo que era Mujer queda Femenino y Sin Información como Sin Información

3. Error al elegir el formato
* Las mismas condiciones del caso 1
* Al elegir el formato se elige erradamente Hombre-Mujer-Sin Información

Sería mejor que importara y agregara el problema, cuando lo detecta, como etiqueta y dejara sexo S.

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2022-07-15 14-57-56](https://user-images.githubusercontent.com/12545631/179302023-9825fec1-8c5e-4913-8cd9-dbfd5321ba1a.png)

**Comment by vtamara** [comment]
Se pruba integrando #765 pero:
1. Debe corregir  formado->formato
  ![image](https://user-images.githubusercontent.com/701221/180097273-d77f4560-765a-47c9-8abd-4e1a448a7d10.png)
2. Bien  #765 o bien a #766  o una mezcla daño la alerta que se presentaba cuando el relato no tenía errores de sintaxis que indicaba cuanto se había importado, la otra alerta con el número de errores y el listado estaba limitado a los casos importados.    
  * Se probó con el siguiente XRLAT: [1066.zip](https://github.com/pasosdeJesus/sivel2_gen/files/9154953/1066.zip)
  *  Con formato de sexo Masculino-Femenino-Sin Información: 
    ![image](https://user-images.githubusercontent.com/701221/180097588-b4300950-0c34-473e-b40c-0121df996c42.png)
  * Tras presionar el botón importar, se redirige al listado de casos pero no presenta alerta indicando si fallo o si logró importar.
![image](https://user-images.githubusercontent.com/701221/180097734-b565ff35-6557-4017-8094-d74e40af9baa.png)

**Comment by vtamara** [comment]
Los 2 errores reportados en https://github.com/pasosdeJesus/sivel2_gen/issues/717#issuecomment-1190857827  fueron resueltos con #770

**Comment by vtamara** [comment]
El relato adjunto tiene sexo F a manera de ejemplo, al importarse indicando que el sistema del cual procede usa formato Mujer-Hombre-Sin Información falla en sitio de producción con:
```
La validación falló: En 'Persona' falta un valor para 'Sexo'
```

![image](https://user-images.githubusercontent.com/701221/180100484-6dc83b2d-70c3-42ac-8797-e52030b74a9a.png)


En tal caso se había solicitado que dejara sexo S y agregar etiqueta de error indicando que el sexo F es desconocido en el formato Mujer-Hombre-Sin Información.

**Comment by vtamara** [comment]
Persiste problema eleigiendo H-M-S e intentando importar:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE relatos SYSTEM "http://sincodh.pasosdejesus.org/relatos/relatos-099.dtd">
<relatos>
     <relato>
       <organizacion_responsable>Banco de Datos del CINEP</organizacion_responsable>
       <derechos>Creative Commons Atribución 2.5 Colombia. http://creativecommons.org/licenses/by/2.5/co/</derechos>
       <id_relato>1066</id_relato>
       <forma_compartir>publico</forma_compartir>
       <titulo>Asesinato casa de Habitación</titulo>
       <hechos>En la casa de Habitación del Señor Diego Fernando Chipatecue Garcia, hombres armados incurren ocacionandole la muerte de manera inmediata 
     este hecho se registra sobre las 4:30 pm del dia viernes, frente a su familia. en Zona Urbana del municipio de San Miguel Putumayo. </hechos>
       <!-- Victimas personas individuales -->
       <persona>
         <id_persona>1739</id_persona>
         <nombre>Diego Fernando</nombre>
         <apellido>Chipatecue Garcia</apellido>
         <docid>CC 14797839</docid>
         <fecha_nacimiento>-00-00</fecha_nacimiento>
         <sexo>F</sexo>
         <observaciones tipo="etnia">SIN INFORMACIÓN</observaciones>
       </persona>
       <!-- Grupos victimizados -->
       <!-- Presuntos responsables -->
       <!-- Victima Individual -->
       <victima>
         <id_persona>1739</id_persona>
         <ocupacion>SIN INFORMACIÓN</ocupacion>
         <sector_condicion>SIN INFORMACIÓN</sector_condicion>
         <iglesia>SIN INFORMACIÓN</iglesia>
         <organizacion>SIN INFORMACIÓN</organizacion>
         <observaciones tipo="filiacion">SIN INFORMACIÓN</observaciones>
         <observaciones tipo="vinculoestado">SIN INFORMACIÓN</observaciones>
         <observaciones tipo="anotaciones"></observaciones>
         <observaciones tipo="organizacion_armada">35</observaciones>
         <observaciones tipo="rangoedad">SIN INFORMACIÓN</observaciones>
       </victima>
       <!-- Ubicacion -->
       <fecha>2022-04-29</fecha>
       <hora>04:30 pm</hora>
       <duracion></duracion>
       <departamento>Putumayo</departamento>
       <municipio>San Miguel</municipio>
       <centro_poblado>La Dorada</centro_poblado>
       <longitud>-76.88302238039196</longitud>
       <latitud>0.33955040373621226</latitud>
       <!-- Actos con Victimas Individuales -->
       <!-- Actos con Victimas Colectivas -->
       <!-- Combatientes -->
       <!-- Otros -->
       <observaciones tipo="grconfiabilidad"></observaciones>
       <observaciones tipo="gresclarecimiento"></observaciones>
       <observaciones tipo="grimpunidad"></observaciones>
       <observaciones tipo="grinformacion"></observaciones>
       <observaciones tipo="bienes"></observaciones>
       <observaciones tipo="intervalo">SIN INFORMACIÓN</observaciones>
       <observaciones tipo="region">BAJO PUTUMAYO</observaciones>
       <observaciones tipo="sitio"></observaciones>
       <observaciones tipo="lugar"></observaciones>
       <observaciones tipo="tsitio">URBANO</observaciones>
     </relato>
</relatos>

```

**Comment by vtamara** [comment]
Resuelto.
