### ISSUE TITLE
F-722 En SIVeL 2.1, formulario caso, pestaña ubicación, al agregar una nueva no comienza con el país Colombia como si ocurre con SIVeL 2.0 [0,6]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#722]

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2022-04-25 18-32-08](https://user-images.githubusercontent.com/12545631/165191074-59a85efa-0d7a-4a8e-916b-a13bc795bec7.png)
