### ISSUE TITLE
F-724 Al crear nueva region  los departamentos a veces se ven con el pais y a veces no, la primera vez se ve con pais, y si lo borramos y lo volvemos a crear ya se ve sin pais

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#724]
![Captura de pantalla de 2022-04-28 20-26-49](https://user-images.githubusercontent.com/10052756/165872565-7aad37a0-5aba-46b3-b615-ce68257f6bf4.png)
![Captura de pantalla de 2022-04-28 20-27-49](https://user-images.githubusercontent.com/10052756/165872566-676f72ba-53aa-4c30-b8f1-dcc4347ab874.png)

**Comment by vtamara** [comment]
Esperamos haber resuelto con #724
