### ISSUE TITLE
R-733  En formulario caso, pestaña víctima, agregar organización social secundaria de selección múltiple. Actualizar documentación. [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#733]

**Comment by vtamara** [comment]
Ya estaba implementado en 2.0

**Comment by alejocruzrcc** [comment]
![Uploading Captura de pantalla de 2022-06-10 20-09-55.png…]()

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2022-06-10 20-09-55](https://user-images.githubusercontent.com/12545631/173220129-95831b4f-cafd-4ca5-8fe4-1a1a0305de48.png)
