### ISSUE TITLE
F-745 Como usuario operador en reportes y conteos, victimas y casos. Al seleccionar un filtro no opera y en ocasiones aparece un mensaje de error entrando con sivel. Y con operador en reportes y conteos, seleccionamos: conteo demografia victimas o conteo de victimizaciones individuales o conteo general de victimizaciones y en todos tres genera error 

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#745]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2022-06-03 19-03-58](https://user-images.githubusercontent.com/10052756/171970320-021423fa-765e-4fc6-812b-45838185bcfb.png)

**Comment by vtamara** [comment]
No reproducible.

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2022-08-25 17-49-01](https://user-images.githubusercontent.com/10052756/186782086-606f3355-30a7-4df6-a7f9-6d48d4a5305d.png)

**Comment by vtamara** [comment]
No falla en 2.1

**Comment by vtamara** [comment]
En 2.2 demografía de víctima con rol operador no presenta gráfica. Reportado en https://gitlab.com/pasosdeJesus/sivel2_gen/-/issues/485

Ya no falla victimas y casos.

Ya no falla conteo general ni victimizaciones individuales con rol operador.
