### ISSUE TITLE
R-750 Al importar un grupo de relatos, antes de hacer la importación como tal, validar el documento completo y presentar errores de sintaxis o validación con número de línea [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#750]
Investigar primero si es posible con nokogiri, si no presentar el reporte de la herramienta xmllint (si no está presentar un mensaje indicandolo). Al usarla además de verificar sintaixs verificar DTD.

**Comment by alejocruzrcc** [comment]
Ejemplo con documento con errores de sintaxis:

![Captura de pantalla de 2022-07-12 14-49-04](https://user-images.githubusercontent.com/12545631/178770733-e819ab8c-79f4-472a-9311-dad5be62c8e7.png)

**Comment by vtamara** [comment]
Cerrado con #766
