### ISSUE TITLE
F-756 En tablas basicas, tabla regiones, en el campo departamentos completos a veces se ve el departamento y a veces el departamento con el pais

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#756]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2022-06-28 10-57-11](https://user-images.githubusercontent.com/10052756/176226891-50f837a9-51ae-4173-9171-0244fa6df719.png)
![Captura de pantalla de 2022-06-28 10-58-09](https://user-images.githubusercontent.com/10052756/176226895-cbf86d37-c905-472a-8b6a-6b5630792cdd.png)

**Comment by vtamara** [comment]
Creo que ya se logró resolver.
