### ISSUE TITLE
F-757  En tablas basicas, tabla categorias, en el campo columna en lista de victimas y casos a veces se ve 7- AMENAZAS y a veces se ve 13- AMENAZAS 

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#757]
![Captura de pantalla de 2022-06-27 08-59-20](https://user-images.githubusercontent.com/10052756/176239085-a36bfcae-fbd3-482f-bb3c-a42d22c2a632.png)

**Comment by vtamara** [comment]
No reproducible. Puede tratarse de una diferencia de un sitio de prueba a otro entre las tablas básicas Rotulos para el listado de víctimas y casos.
