### ISSUE TITLE
F-758 En Desaparicion, en Lugar preliminar de disposición irregular de cadáveres, en la seccion de antecedentes proporcionados por el aportante se ven dos tablas en la misma linea y se confunden.

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#758]
![Captura de pantalla de 2022-06-28 17-40-43](https://user-images.githubusercontent.com/10052756/176317913-cdd7ba1d-d204-4ce9-b69f-b3dc8182b314.png)

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/179895251-8cb4fe20-4a57-4f24-b607-598f8cc9a260.MOV
