### ISSUE TITLE
R-762 En formulario caso pestaña combatiente por cada combatiente agregar botón Crear Copia análogo al de víctima [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#762]

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2022-08-25 02-01-12](https://user-images.githubusercontent.com/12545631/186597520-683a71bc-567e-4b8b-b565-22d810f434e8.png)

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2022-08-25 02-20-13](https://user-images.githubusercontent.com/12545631/186601139-a3e83759-ece9-4380-84a4-f9a472c8d025.png)

**Comment by vtamara** [comment]
Avance con #790

**Comment by vtamara** [comment]
Al crear una copia de un combatiente con información completa y guardar, si queda la copia, pero se pierde la información del combatiente original.  Ver video 

https://user-images.githubusercontent.com/701221/186624872-166d5124-b9ea-497e-9725-52a7ad77d351.mp4

**Comment by vtamara** [comment]
Arreglado con #800
