### ISSUE TITLE
F-774 El control de autocompletación de personas no opera en sivel2 como si lo hace en Apo214. [1] 

### ISSUE THREAD

**Issue by alejocruzrcc** [pasosdeJesus/sivel2_gen#774]

**Comment by vtamara** [comment]
Pantallazo o video por favor?

**Comment by vtamara** [comment]
Parece que se resuelve con https://github.com/pasosdeJesus/apo214/pull/68

**Comment by alejocruzrcc** [comment]
con https://github.com/pasosdeJesus/apo214/pull/72

https://user-images.githubusercontent.com/12545631/195804556-2804d992-38e5-4213-83ec-ac53b9de991a.MOV

**Comment by vtamara** [comment]
![prob-auto-lug-sivel2](https://user-images.githubusercontent.com/701221/196044043-685ed7b3-b889-4826-b588-8f8a3b38ed9b.png)

**Comment by vtamara** [comment]
Tras mezclar https://github.com/pasosdeJesus/apo214/pull/72  y regenerar recursos opera en sivel2.
