### ISSUE TITLE
F-777 En formulario caso, pestaña víctima, no permite buscar  (ni autocompletar) familiar [4]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#777]

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/184463364-484349b8-6c58-4c36-9bda-33363254b329.MOV

**Comment by vtamara** [comment]
Propuesta de solución con #783

**Comment by vtamara** [comment]
Tras mezclar persiste el problema: 
![2opfalla](https://user-images.githubusercontent.com/701221/184891664-73d433a5-0aab-4744-8d47-bb50ba9f36e7.png)

**Comment by vtamara** [comment]
Presenta error 
![sigue](https://user-images.githubusercontent.com/701221/184891834-76343de7-02e1-4239-a0b4-1a4d999f97cb.png)

**Comment by vtamara** [comment]
Luis Alejandro indica que lo arregló para nuevas víctimas pero no para existentes.

**Comment by vtamara** [comment]
Completada con #799
