### ISSUE TITLE
F-778 Al importar o exportar usar la convención para sexo del sistema, ver #716 [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#778]

**Comment by alejocruzrcc** [comment]
Para la configuración del sistema MHS se probaron los 4 casos.
Formatos coinciden: 

https://user-images.githubusercontent.com/12545631/182764757-df9aa3ff-cb17-43b8-ab67-2a0460829cce.MOV


https://user-images.githubusercontent.com/12545631/182764814-e75c2686-dc24-45f5-b45c-9d0b47678f82.MOV


Formatos NO coinciden (se pone mal, o se creea etiqueta de advertencia):

https://user-images.githubusercontent.com/12545631/182764874-9411cbd7-afd2-474e-a593-637189cf2f9a.MOV


https://user-images.githubusercontent.com/12545631/182764911-a5f7f5ef-9dc3-409c-866c-53ee47dd9f73.MOV

**Comment by alejocruzrcc** [comment]
Para exportaciones, funciona bien: Sistema configurado como HMS:

![Captura de pantalla de 2022-08-03 23-59-48](https://user-images.githubusercontent.com/12545631/182766709-944e6aeb-9be6-4db9-8142-c79ffea9d03d.png)
![Captura de pantalla de 2022-08-03 23-54-31](https://user-images.githubusercontent.com/12545631/182766712-1a72605e-f078-40b6-9724-282a7f086f90.png)

**Comment by alejocruzrcc** [comment]
Sistema configurado como FMS:
 
![Captura de pantalla de 2022-08-04 00-04-09](https://user-images.githubusercontent.com/12545631/182767109-d8e00958-cdb9-4514-a241-0aa9c5f2b2cb.png)
![Captura de pantalla de 2022-08-04 00-03-26](https://user-images.githubusercontent.com/12545631/182767112-4f41252a-ea0c-447d-a0ba-0f2d437595c2.png)

**Comment by vtamara** [comment]
Propuesta de solución https://github.com/pasosdeJesus/sivel2_gen/pull/779

**Comment by vtamara** [comment]
Bien, pero en caso de error el sexo que aparecía en el archivo debería mencionarse en la observación de la etiqueta.
![image](https://user-images.githubusercontent.com/701221/183473391-074c4456-add1-401b-bbaa-d005ca188f8a.png)

Y no se trata de formato, es una convención

Algo como "Sexo Q no corresponde a la convención elegida (MHS)"

**Comment by vtamara** [comment]
Completado con #784
