### ISSUE TITLE
R-780 En formulario de disposición de cadáveres cambiar formulario para que los campos nuevos queden en la tabla como última fila con un botón Añadir [1,6]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#780]

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/188804239-e3562a5d-42cb-439f-9f19-ec11f4d2381c.MOV

**Comment by vtamara** [comment]
De lo que se ve en el vídeo me parece que va bien. Mejor que:
* El último quede al final de la tabla y  no al comienzo.
* Lo otro que no se ve en el video es la autocompletación para agregar personas que ya existan. No es necesario que ponga placeholders Nombres Apellidos Sexo Organización en los campos porque ya está en el título de la columna. Pero si deje Buscar en el campo en el que se puede buscar para autocompletación porfa.

**Comment by vtamara** [comment]
Propuesta de completación con https://github.com/pasosdeJesus/apo214/pull/71

**Comment by vtamara** [comment]
Ya el último queda al final de la tabla.
Para la parte de autocompletacioń se crearon #804 y #805
