### ISSUE TITLE
F-789 En el formulario de caso con operario no se puede agregar una etu¡iqueta, generaverror

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#789]
![Captura de pantalla de 2022-08-22 17-39-27](https://user-images.githubusercontent.com/10052756/186031774-b2f20e36-1e0b-43cc-af3d-cc77f1f80ce6.png)

**Comment by vtamara** [comment]
Resuelto. Faltaba desplegarlo.
