### ISSUE TITLE
F-801 Formulario de Asistentes en Formulario de desaparaición no opera en aplicación de prueba, y en sivel2 no agrega dinámicamene asistente. [2]

### ISSUE THREAD

**Issue by alejocruzrcc** [pasosdeJesus/sivel2_gen#801]

**Comment by alejocruzrcc** [comment]
![photo1662074478](https://user-images.githubusercontent.com/12545631/188248502-c8aa1d03-3697-423a-b6a4-dfd351615b4d.jpeg)

**Comment by vtamara** [comment]
Propuesta de solución https://github.com/pasosdeJesus/apo214/pull/69/files

**Comment by vtamara** [comment]
Opera en ambos, pero se trata de controladores duplicados.
