### ISSUE TITLE
R-804 En resumen de una persona (vista show) presentar lugares preliminares donde la persona aparece como asistente [0,8]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#804]

**Comment by alejocruzrcc** [comment]
![Captura de pantalla de 2022-10-14 00-26-08](https://user-images.githubusercontent.com/12545631/195769094-9642caa7-0e6a-47b0-8cd0-3cc602d26b3a.png)

**Comment by vtamara** [comment]
En el ejemplo que hice en apo214, agregué organización x en el formulario:
![image](https://user-images.githubusercontent.com/701221/196047253-0db8142c-6983-4f93-9abf-24e8e23f3e29.png)

Pero no se ve en la vista de persona:

![image](https://user-images.githubusercontent.com/701221/196047298-6ae31f92-cdc1-4ef3-b075-d0342fe852cc.png)

**Comment by vtamara** [comment]
En el resumen el título en lugar de ser "Lugares preliminares" debería ser algo como "Asistencia a registro de lugares preliminares de disposición de cadáveres"

**Comment by vtamara** [comment]
Propuesta de mejora con https://github.com/pasosdeJesus/apo214/pull/73
