### ISSUE TITLE
R-805 En lugar preliminar, listado de asistentes usar nuevo control de autocompletación [3]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#805]
![image](https://user-images.githubusercontent.com/701221/196046062-a9779b64-0554-4315-867e-fc0924467751.png)

**Comment by alejocruzrcc** [comment]
Desde aplicación de prueba de apo:
https://user-images.githubusercontent.com/12545631/198119014-71eb803b-e39c-4e9d-859e-105cefd10f79.MOV

**Comment by alejocruzrcc** [comment]
En sivel2:

https://user-images.githubusercontent.com/12545631/198120740-1aeafc34-30e6-4e77-af63-1f25ee891340.MOV

**Comment by vtamara** [comment]
Propuesta con https://github.com/pasosdeJesus/apo214/pull/75
