### ISSUE TITLE
R-814 Que nuevo campo subdivisión de caso presponsable sirva para importar y exportar relatos [1]

### ISSUE THREAD

**Issue by alejocruzrcc** [pasosdeJesus/sivel2_gen#814]

**Comment by alejocruzrcc** [comment]
Importado: 

![Captura de pantalla de 2022-10-05 15-30-09](https://user-images.githubusercontent.com/12545631/194157664-b0898a29-2045-47e2-a1de-6b6e0a0bab91.png)

**Comment by alejocruzrcc** [comment]
Exportado:

       <grupo>
         <id_grupo>104</id_grupo>
         <nombre_grupo>Águilas Negras</nombre_grupo>
         <observaciones tipo="subdivision">division1.brigada1.batallon1</observaciones>
         <observaciones tipo="bloque">bloque1</observaciones>
         <observaciones tipo="frente">frente1</observaciones>
         <observaciones tipo="otro"></observaciones>
       </grupo>
       <grupo>
         <id_grupo>4</id_grupo>
         <nombre_grupo>Ejército</nombre_grupo>
         <observaciones tipo="subdivision">division.brigada.batallon</observaciones>
         <observaciones tipo="bloque">bloque</observaciones>
         <observaciones tipo="frente">frente</observaciones>
         <observaciones tipo="otro"></observaciones>
       </grupo>
       <grupo>
         <id_grupo>28</id_grupo>
         <nombre_grupo>ELN</nombre_grupo>
         <observaciones tipo="subdivision">una division</observaciones>
         <observaciones tipo="bloque">dfk</observaciones>
         <observaciones tipo="frente">okd</observaciones>
         <observaciones tipo="otro"></observaciones>
       </grupo>

**Comment by alejocruzrcc** [comment]
https://github.com/pasosdeJesus/sivel2_gen/pull/815

**Comment by vtamara** [comment]
Se ve operando.
