### ISSUE TITLE
F-816 El formulario de casos no permite adjuntar pdf, docx ni formatos diferentes a .jpg, .png y .zip (Fabiana)

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#816]
![image](https://user-images.githubusercontent.com/701221/194407492-bc1e9462-63cd-4e0b-8084-b954ac90e445.png)

**Comment by vtamara** [comment]
Resuelto con https://github.com/pasosdeJesus/apo214/commit/414a495f264773983741fa18b59578f5072a59d7

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2023-01-03 10-47-14](https://user-images.githubusercontent.com/10052756/210680926-1e2ce8e6-6811-4a90-a349-4b3848122035.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2023-01-04 20-32-50](https://user-images.githubusercontent.com/10052756/210681496-270cd4d1-ddf5-4216-9c36-d4e0557dc072.png)
