### ISSUE TITLE
En mapa al refrescar la página algunas veces, aparece alert de error que no encuentra la ruta y posteriormente no muestra ningún caso.

### ISSUE THREAD

**Issue by alejocruzrcc** [pasosdeJesus/sivel2_gen#82]
![Captura de pantalla de 2020-02-20 13-56-55](https://user-images.githubusercontent.com/12545631/74968848-8873d780-53e9-11ea-8259-fc51c76b0004.png)

Se propone arreglar en https://github.com/pasosdeJesus/sivel2_gen/pull/76

**Comment by vtamara** [comment]
Este error no ocurre con firefox 69.02 en adJ.
Si ocurre con chromium 79.0.3945.117 en adJ.
En Linux con .. también ocurre.
Tanto en adJ con chromium 79.0.3945.117 como en Linux con chrome 79.0.3945.117  no ocurre el error si se inspecciona el código y se pone un punto de ruptura en la función sip_prepara_eventos_comunes después de root.puntomontaje = ...  como se muestra en imagen.
![ruptura](https://user-images.githubusercontent.com/701221/74985402-60926d00-5405-11ea-9da3-07bdc1516ce5.png)


Se concluye que es un error en chromium/chrome.
