### ISSUE TITLE
R-820 En resumen de caso, en la previsualización de anexos, de los PDF extraer primera página como imagen y previsualizar en 2/3  del ancho del navegador  para que siempre sean visibles botones Cancelar y Descargar [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#820]
En imagenes anchas si se escala la previsualización como se esperaba:
![image](https://user-images.githubusercontent.com/701221/196041352-5ada44de-9e6d-4209-94f8-8dc1b879193a.png)

Pero los PDF anchos no están escalando y ocultan los botones de Cancelar, Descargar como se ve en la siguiente imagen:

![image](https://user-images.githubusercontent.com/701221/196040653-4dd7d9a4-c4c8-4094-9c35-55af3eb4ffb0.png)

Debería escalarse a lo ancho para que el máximo sea por ejemplo 2/3 del ancho de la pantalla de manera que siempre sean visibles los botoenes Cancelar y Descargar.

**Comment by vtamara** [comment]
Se adjunta PDF ancho
[19464_3222_116_-_135._Águilas_Negras_amenazan_de_muerte_a_Gustavo_Petro__Francia_Márquez_y_otros_miembros_del_Pacto_Histórico_-_Infobae.pdf](https://github.com/pasosdeJesus/sivel2_gen/files/9794832/19464_3222_116_-_135._Aguilas_Negras_amenazan_de_muerte_a_Gustavo_Petro__Francia_Marquez_y_otros_miembros_del_Pacto_Historico_-_Infobae.pdf)

**Comment by vtamara** [comment]
El PR propuesto #828 no resuelve, el PDF ancho ajduntado se ve así:
![prob-pdf2](https://user-images.githubusercontent.com/701221/197783100-ab96e79e-03f6-42a7-a082-b785d7d8524b.png)

**Comment by vtamara** [comment]
Como es una previsualización de un PDF, considero que bastaría previsualizar la primera página. Por ejemplo extrayendola del PDF y convirtiendola a jpg y previsualizar esa como se haría con imágenes que ya está operando bien.

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/198363950-b94d8b1b-ded6-41e7-a2ee-2fe927a412c2.MOV

**Comment by vtamara** [comment]
Implementación se ve operando con https://github.com/pasosdeJesus/sivel2_gen/pull/833

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2023-01-04 21-16-31](https://user-images.githubusercontent.com/10052756/210686446-07746315-d360-4360-95fc-15bcd07f9e39.png)
