### ISSUE TITLE
F-823 En formulario de lugares preliminares no presenta errores al comienzo del formulario [0,8]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#823]
Por ejemplo cuando se ingresa una persona inhumada sin apellido al guardar queda una alerta en blanco al comienzo del formulario 

![image](https://user-images.githubusercontent.com/701221/196047985-87607b25-a0b7-4008-8fb6-51891b76ba05.png)

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/233241453-c1d6ba79-e839-4da1-85ae-03996c0bc28f.mp4
