### ISSUE TITLE
R-825 En rama msip, en el formulario caso cambiar la pestaña Fuentes Frecuentes para que no use jquery ni cocoon sino Turbo y Stimulus [5,4]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#825]

**Comment by alejocruzrcc** [comment]
[purebafprensa.webm](https://user-images.githubusercontent.com/12545631/206801365-ca5eea92-5125-4a4d-b3e4-c9166ad79718.webm)

**Comment by vtamara** [comment]
Implementación inicial en https://github.com/pasosdeJesus/sivel2_gen/pull/866
