### ISSUE TITLE
F-834 Formulario de lugar preliminar, listado de asistentes no permite poner de primero un asistente [0,6]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#834]
El que se pone de primeras, tras guardar y ediitar queda de segundo.

**Comment by vtamara** [comment]
https://user-images.githubusercontent.com/701221/198185115-89fc7438-4e73-4db1-93b8-105ec451718f.mp4

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/233221609-5686c895-cbc3-47de-9832-bf09e568724a.mp4

**Comment by vtamara** [comment]
A mi no me opera.

**Comment by vtamara** [comment]
Movido a https://gitlab.com/pasosdeJesus/sivel2_gen/-/issues/490
