### ISSUE TITLE
F-837 Previsualización de anexos no presenta bien algunos PDFs.  Y tipos que no sean imagenes ni PDF deberían presentar sólo un enlace de descarga  [0,8]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#837]
Por ejemplo el siguiente PDF 

[US Faith Leaders Letter - Hands Off Colombia.pdf](https://github.com/pasosdeJesus/sivel2_gen/files/9892175/US.Faith.Leaders.Letter.-.Hands.Off.Colombia.pdf)

se ve asi:

![image](https://user-images.githubusercontent.com/701221/198739893-a57f455c-0eae-4e4e-b467-b11af2eaf161.png)

**Comment by vtamara** [comment]
Y un texto se ve así:
![image](https://user-images.githubusercontent.com/701221/198740041-536c5336-86bc-4ad2-8b96-ad3df7480570.png)

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/199878538-8bc6374f-d01b-472e-9e74-c916bc3432d5.MOV

**Comment by vtamara** [comment]
La siguiente imagen
![20586_photo_5163723654406711895_x(2)](https://user-images.githubusercontent.com/701221/202189588-53bd7e33-e830-4403-b3f5-5b5df5594e44.jpg)


al anexarla se ve así:

![image](https://user-images.githubusercontent.com/701221/202189460-525b0ee8-a6bf-4005-8469-0151a7d07496.png)

**Comment by vtamara** [comment]
Propuesta de implementación  con https://github.com/pasosdeJesus/sivel2_gen/pull/840

**Comment by vtamara** [comment]
> La siguiente imagen ![20586_photo_5163723654406711895_x(2)](https://user-images.githubusercontent.com/701221/202189588-53bd7e33-e830-4403-b3f5-5b5df5594e44.jpg)
> 
> al anexarla se ve así:
> 
> ![image](https://user-images.githubusercontent.com/701221/202189460-525b0ee8-a6bf-4005-8469-0151a7d07496.png)

Persiste problema con esa imagen.

**Comment by vtamara** [comment]
Propuesta de mejora con https://github.com/pasosdeJesus/sivel2_gen/pull/850

**Comment by vtamara** [comment]
Se ven bien PDFs y jpgs de diversos tamaños.
