### ISSUE TITLE
F-845 No sobrecargar en apo214 la función remplazar de personas_controller o al menos no sin cuidado, porque daña funcionalidad de autocompletar víctima en formulario de caso [0,6]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#845]
Ver #844

**Comment by vtamara** [comment]
Se renombró remplazar por remplazar_apo214 en personas_controller.rb
Así mismo personas_controller.rb debe descender de Sivel2Gen::PersonasController y no de Sip::PersonasController o se perderá la funcionalidad que añade sivel2_gen.

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/218137550-d0a8e788-4908-4f47-a4ce-4b5016f8a161.mp4

**Comment by vtamara** [comment]
Tras el cambio que haga debe probar autocompletar víctima en el formulario persona y hacer video de eso operando.

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/222340161-4f6b5941-1ee3-481c-bebd-99ccdac21373.mp4

**Comment by vtamara** [comment]
Aun no funciona todo.

Si me funcionó autocompletación de:
* nombre de víctima en formulario caso
* lugar preliminar -> antecedentes aportados por el aportante ->  Añadir Depositado

Pero no funcionó en Lugar Preliminar->Datos del aportante pues aparece:
![prob-autocomp](https://user-images.githubusercontent.com/701221/230254496-a1044d9f-15d0-49bb-9fa4-f658fde84254.png)


Al intentar autocompletar datos del aportante:

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/233216971-e46cbc35-1e13-4e27-a3b3-33098044e82a.mp4

**Comment by vtamara** [comment]
Movido a https://gitlab.com/pasosdeJesus/sivel2_gen/-/issues/493
