### ISSUE TITLE
R-846 En formulario caso y en otros formularios botones interiores con estilo común [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#846]
En formulario agregar bootstrap el estilo de botones en tablas que se amplian, i.e Ubicación, Fuentes Frecuentes, Otras Fuentes, Presuntos Respnosables, Víctimas, Víctimas Colectivas, Combatientes, Anexos, Etiquetas, Solicitudes.  

Replicar a otros botones análogos en motores.

En pestaña acto, disminuir tamaño de botones agregar y eliminar.

**Comment by vtamara** [comment]
En sip
- [x] Anexo
- [x] Campos automaticos
- [x] Contacto de organización social
- [x] Respaldo
- [x] Solicitudes

![image](https://user-images.githubusercontent.com/701221/202325155-8d7c3ece-973d-4a3a-92e0-12e995f69034.png)

En mr519_gen
- [x] encuestapersona
- [x] campo dinámico

En heb412_gen
- [ ]

**Comment by vtamara** [comment]
Implementando

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2023-01-04 21-32-28](https://user-images.githubusercontent.com/10052756/210688297-194132d6-b2f8-4472-ab60-c9cffc9d1ee3.png)
![Captura de pantalla de 2023-01-04 21-32-04](https://user-images.githubusercontent.com/10052756/210688302-248336dc-34e4-457d-b1c3-6123f289a843.png)
![Captura de pantalla de 2023-01-04 21-31-39](https://user-images.githubusercontent.com/10052756/210688304-f3f3e07a-4904-4ff4-bf06-efc3c9cee7e4.png)
