### ISSUE TITLE
F-861 No está operando control para elegir categoría de violencia en Conteo de victimizaciones individuales cuando el punto de montaje es diferente a /sivel2 [0,8]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_gen#861]

**Comment by vtamara** [comment]
![image](https://user-images.githubusercontent.com/701221/217968909-c8b97b75-40c2-423d-abfb-4e8f9ec41c36.png)

**Comment by alejocruzrcc** [comment]
https://user-images.githubusercontent.com/12545631/218117627-36dc9781-c09c-4eea-9a0f-079ed18adc35.mp4

**Comment by vtamara** [comment]
En el pantallazo de ejemplo que puse en el que falla el punto de montaje es el estándar para la actual rama main `sivel2_2`

**Comment by vtamara** [comment]
Si funciona, al parece lo que falta en algunas aplicaciones que emplean sivel2_gen es agregar `sivel2_gen/motor2` en `app/assets/javascript/recursos_sprockets.js`
