### ISSUE TITLE
F-873 En formulario casos, victimas no estan llenando automáticamente Edad en fecha del hecho y Edad/aniversario actual 

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#873]
![Captura de pantalla de 2022-12-21 09-56-12](https://user-images.githubusercontent.com/10052756/208935097-dc563be2-e85e-40d6-9597-b3bbadf5b659.png)

**Comment by vtamara** [comment]
Ahora opera sin problema en 2.2
