### ISSUE TITLE
F-875 En Reportes, conteos, demografia de victimas, victimizaciones individuales y conteo general de victimizaciones genera error con usuario operador

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/sivel2_gen#875]
![Uploading Captura de pantalla de 2022-12-31 10-16-38.png…]()

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2022-12-31 10-16-38](https://user-images.githubusercontent.com/10052756/210141494-b5c31483-ae0e-4a95-b33c-509629c42705.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2022-12-31 14-25-24](https://user-images.githubusercontent.com/10052756/210153940-e2b757ac-437c-417d-8708-bac1280d48ac.png)
![Captura de pantalla de 2022-12-31 14-24-46](https://user-images.githubusercontent.com/10052756/210153943-e7fc656c-a217-44d0-a928-88a3fdf02a5f.png)
![Captura de pantalla de 2022-12-31 14-22-33](https://user-images.githubusercontent.com/10052756/210153944-5b2d2eeb-bd89-4b99-a254-db534d19d109.png)

**Comment by vtamara** [comment]
Resuelto en 2.1 y 2.2.
